.PHONY: clean All

All:
	@echo "----------Building project:[ maxSum - Debug ]----------"
	@cd "maxSum" && $(MAKE) -f  "maxSum.mk"
clean:
	@echo "----------Cleaning project:[ maxSum - Debug ]----------"
	@cd "maxSum" && $(MAKE) -f  "maxSum.mk" clean
