.PHONY: clean All

All:
	@echo "----------Building project:[ matrixLinkMultiplication - Debug ]----------"
	@cd "matrixLinkMultiplication" && $(MAKE) -f  "matrixLinkMultiplication.mk"
clean:
	@echo "----------Cleaning project:[ matrixLinkMultiplication - Debug ]----------"
	@cd "matrixLinkMultiplication" && $(MAKE) -f  "matrixLinkMultiplication.mk" clean
