.PHONY: clean All

All:
	@echo "----------Building project:[ findMedianOfAnArray - Debug ]----------"
	@cd "findMedianOfAnArray" && $(MAKE) -f  "findMedianOfAnArray.mk"
clean:
	@echo "----------Cleaning project:[ findMedianOfAnArray - Debug ]----------"
	@cd "findMedianOfAnArray" && $(MAKE) -f  "findMedianOfAnArray.mk" clean
