.PHONY: clean All

All:
	@echo "----------Building project:[ 3_LongestSubstringWithoutRepeatingCharacters - Debug ]----------"
	@cd "3_LongestSubstringWithoutRepeatingCharacters" && $(MAKE) -f  "3_LongestSubstringWithoutRepeatingCharacters.mk"
clean:
	@echo "----------Cleaning project:[ 3_LongestSubstringWithoutRepeatingCharacters - Debug ]----------"
	@cd "3_LongestSubstringWithoutRepeatingCharacters" && $(MAKE) -f  "3_LongestSubstringWithoutRepeatingCharacters.mk" clean
