.PHONY: clean All

All:
	@echo "----------Building project:[ 4_MedianOfTwoSortedArrays - Debug ]----------"
	@cd "4_MedianOfTwoSortedArrays" && $(MAKE) -f  "4_MedianOfTwoSortedArrays.mk"
clean:
	@echo "----------Cleaning project:[ 4_MedianOfTwoSortedArrays - Debug ]----------"
	@cd "4_MedianOfTwoSortedArrays" && $(MAKE) -f  "4_MedianOfTwoSortedArrays.mk" clean
