.PHONY: clean All

All:
	@echo "----------Building project:[ 1_TwoSum - Debug ]----------"
	@cd "1_TwoSum" && $(MAKE) -f  "1_TwoSum.mk"
clean:
	@echo "----------Cleaning project:[ 1_TwoSum - Debug ]----------"
	@cd "1_TwoSum" && $(MAKE) -f  "1_TwoSum.mk" clean
